### PR TITLE
Rename README.md to jieke008.md

### PR DESCRIPTION
**Pull request by yongjie917**

### CODE REVIEW

**Comment by yongjie917** [comment]
[https://github.com/easemob/easeui_ios](https://github.com/easemob/easeui_ios)
diff --git a/jieke008.md b/jieke008.md
new file mode 100644
index 0000000..f2d42ce
--- /dev/null
+++ b/jieke008.md
@@ -0,0 +1,8 @@
+# sdkdemoapp3.0_ios

**Comment by yongjie917** [comment]
From e6715550c04808feb4b55f03411cedb3efb84253 Mon Sep 17 00:00:00 2001
From: yongjie917 yongjie917@icloud.com
Date: Sun, 18 Sep 2016 05:17:23 +0800
Subject: [PATCH] Rename README.md to jieke008.md

**Review by yongjie917 — COMMENTED** [review]
From e6715550c04808feb4b55f03411cedb3efb84253 Mon Sep 17 00:00:00 2001
From: yongjie917 yongjie917@icloud.com
Date: Sun, 18 Sep 2016 05:17:23 +0800
Subject: [PATCH] Rename README.md to jieke008.md

**Comment by githubzhaoliang** [comment]
为什么提这种pr？

**Comment by yongjie917** [comment]
我在学，创建文件

发自我的 iPhone

**Pull request closed without merging**
